services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    env_file:
      - .env

  redis:
    image: redis:7.2.5
    container_name: redis
    ports:
      - "6379:6379"

  #  webserver:
  #    image: pyrender:0.0.1
  #    container_name: webserver
  #    restart: always
  #    ports:
  #      - "5000:5000"
  #    depends_on:
  #      - mysql
  #      - redis
  #    env_file:
  #      - .env
  #    volumes:
  #      - .:/opt/app
  #    command:
  #      - render
  #      - webserver

  scheduler:
    image: pyrender:0.0.1
    container_name: scheduler
    restart: always
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    command:
      - render
      - scheduler

  worker:
    image: pyrender:0.0.1
    container_name: worker
    restart: always
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    command:
      - render
      - worker
