version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: ui_render_mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
      - "33060:33060"
    env_file:
      - .env